kakao:
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  grant-type: authorization_code
  client-id: 0624842a8b478e278f6669ab5bc1a6c5
  redirect-uri: http://localhost:3000/login/